# Connect  to mongodb compass using -
# mongodb://root:finance@localhost:27027/

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 4400:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=finance
    volumes:
      - mongo-data:/data/db

  server:
    build: .
    image: finance-backend:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      - DB_URL=mongodb://root:finance@mongo:27017/finance
      - DOTENV_KEY=dotenv://:key_0fab899c8f32b10ac700d5e2304d488c251b9dd2de08d29a7e36af7061adf57b@dotenv.org/vault/.env.vault?environment=development

volumes:
  mongo-data:
